apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-app
  namespace: kube-practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: practice-app
  template:
    metadata:
      labels:
        app: practice-app
    spec:
      containers:
      - name: practice-app
        image: nginx:stable
        ports:
        - containerPort: 80
