apiVersion: v1
kind: Service
metadata:
  name: practice-app-service
  namespace: kube-practice
spec:
  selector:
    app: practice-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
